=begin
#Search Book API

#API to find library that has searching books.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

module OpenapiClient
  VERSION = '1.0.0'
end
