=begin
#Search Book API

#API to find library that has searching books.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'book_search_api_client/api_client'
require 'book_search_api_client/api_error'
require 'book_search_api_client/version'
require 'book_search_api_client/configuration'

# Models
require 'book_search_api_client/models/library'

# APIs
require 'book_search_api_client/api/v1_api'

module BookSearchApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   BookSearchApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
