=begin
#Search Book API

#API to find library that has searching books.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::V1Api
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'V1Api' do
  before do
    # run before each test
    @api_instance = OpenapiClient::V1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1Api' do
    it 'should create an instance of V1Api' do
      expect(@api_instance).to be_instance_of(OpenapiClient::V1Api)
    end
  end

  # unit tests for get_libraries
  # Returns a list of libraries.
  # @param appkey 
  # @param pref 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :city 
  # @option opts [String] :systemid 
  # @option opts [String] :geocode 
  # @option opts [String] :format 
  # @option opts [String] :callback 
  # @option opts [Integer] :limit 
  # @return [Array<Library>]
  describe 'get_libraries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
